### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by kacperpaluch** [dh024/Bitwarden_Export#1]
Hi,

I try to use you script to backup my Bitwarden but I have an error:
```
bw_export.sh: line 161: syntax error near unexpected token `('
bw_export.sh: line 161: `    bash <(bw list items | jq -r '.[] '
```
the line 161 in my sh file is:
```
bash <(bw list items | jq -r '.[] 
```
My os: macOs 12.5.1

Any idea how to fix it?
![Zrzut ekranu 2022-09-5 o 23 43 29](https://user-images.githubusercontent.com/52283764/188514803-44d6db34-1731-461b-93b6-830163bbc915.png)

**Comment by dh024** [comment]
You need to execute the script as "bash bw_export.sh" not "sh bw_export.sh". If bash doesn't work, you can try /bin/bash instead.

**Comment by kacperpaluch** [comment]
Thank you.
