### ISSUE TITLE
Best way to add multiple Organization IDs?

### ISSUE THREAD

**Issue by Stickyhavr** [dh024/Bitwarden_Export#2]
Hello,
How would I modify the script to export multiple organizations? 

Thanks!

**Comment by dh024** [comment]
I have no way to test this, so I won't be implementing this. But it would be easy to implement yourself if you have some basic bash scripting experience. You would just need to create an array of organization ids in place of the single org_id variable in line 29, and then wrap lines 136 -152 inside a loop that iterates through all the org_ids in the array.
